version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  producer:
    build:
      context: .
      dockerfile: cmd/producer/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: test-cti-records
      CTI_FILE: /app/enterprise-attack.json
    volumes:
      - ./enterprise-attack.json:/app/enterprise-attack.json
    command: ["producer"]

  builder:
    build:
      context: .
      dockerfile: cmd/builder/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: test-cti-records
      DB_PATH: /app/threats.bleve/test_genomes.db
    volumes:
      - ./threats.bleve:/app/threats.bleve
      - ./data:/app/data
    command: ["builder"]

  indexer:
    build:
      context: .
      dockerfile: cmd/indexer/Dockerfile
    depends_on:
      - builder # Indexer depends on builder to have processed data
    environment:
      DB_PATH: /app/threats.bleve/test_genomes.db # Assuming indexer uses the same DB
    volumes:
      - ./threats.bleve:/app/threats.bleve
    command: ["indexer"]

  search:
    build:
      context: .
      dockerfile: cmd/search/Dockerfile
    depends_on:
      - indexer # Search depends on indexer to have built the index
    environment:
      DB_PATH: /app/threats.bleve/test_genomes.db # Assuming search queries the same DB
    volumes:
      - ./threats.bleve:/app/threats.bleve
    ports:
      - "8080:8080" # Example port if search exposes an API
    command: ["search"]